### ISSUE TITLE
Allow scrolling on right navigation TOC in API section

### ISSUE THREAD

**Issue by brandenchan** [deepset-ai/haystack-website#103]
On some pages, the right side TOC is so populated that not all of it can be displayed on a page. It is not currently possible to scroll through this TOC making navigation on this page difficult

e.g. 

https://haystack.deepset.ai/docs/latest/apidatabasemd

**Comment by PiffPaffM** [comment]
This will be part of an upcoming project with a freelancer and is handled in the SOW for it
