### ISSUE TITLE
Custom Nodes in YAML definitions of Pipelines for use with REST API

### ISSUE THREAD

**Issue by Hamcastle** [deepset-ai/haystack-website#147]
Hello! 

Thank you for putting together such an incredible resource, and apologies if this is something that's been addressed in another issue -- checked but didn't see anything exactly related.

Your tutorial on the use of the REST API says that any pipeline used through it needs to be defined in a YAML. Is there support for including custom nodes -- in my case, for example, keyword extraction using Spacy -- in these files? The available tutorials and repository material don't make that look to be the case.

Thanks again!

**Comment by brandenchan** [comment]
Hi @Hamcastle , really sorry that this issue slipped through the cracks. We more regularly check the issues over [here](https://github.com/deepset-ai/haystack/issues). If you open the issue there, we will get back to you within a day!
