### ISSUE TITLE
haystack and fastAPI - urgent help

### ISSUE THREAD

**Issue by shainaraza** [deepset-ai/haystack-website#189]
I have an issue running the haystack with FASTAPI on google colab.
I use the following code and it does not run, I think the issue is not the server error but something wrong in code?
Any help is highlighly appreciated.
I put the notebook here for experts' advice.

https://colab.research.google.com/drive/191cyC5eXajgekBwJKs4hKmAiC_WmHuQ_?usp=sharing

thanks

**Comment by tholor** [comment]
Hey @shainaraza  , this repo is just related to our documentation website. If you have any general questions, please create an issue in the main project repo: https://github.com/deepset-ai/haystack/
Thx!
