### ISSUE TITLE
"Edit on Github" link broken for Guides

### ISSUE THREAD

**Issue by tholor** [deepset-ai/haystack-website#208]
When click on the "Edit on Github" button in a guide, you get redirected to a broken URL (e.g. https://github.com/deepset-ai/haystack-website/blob/source/docs/latest/usage/languages.mdx) 
Seems that the path has changed from `usage` to `guides`

**Comment by DIVYA-19** [comment]
@tholor There is a similar issue #236. I made a PR #245

**Comment by brandenchan** [comment]
Fixed by #245
