### ISSUE TITLE
broken edit link

### ISSUE THREAD

**Issue by koaning** [deepset-ai/haystack-website#236]
I just tried editing [this page](https://haystack.deepset.ai/usage/chatbots) and the button linked me to this URL:

https://github.com/deepset-ai/haystack-website/blob/source/docs/latest/usage/chatbots.mdx

It seems the URL is broken.

**Comment by brandenchan** [comment]
Hi @koaning, apologies for the late reply, I've just come back from vacation. Yes thanks for pointing this out. We will work on fix in the coming days. In the mean time, if you have content suggestions for the chatbots page, this is the file you're looking for! 

https://github.com/deepset-ai/haystack-website/blob/source/docs/latest/guides/chatbots.mdx

**Comment by brandenchan** [comment]
Fixed by #245
