### ISSUE TITLE
Better management of Right Table of Contents when too long

### ISSUE THREAD

**Issue by brandenchan** [deepset-ai/haystack-website#279]
- In situations where the right ToC has many entries, it can often extend beyond the window
- Design a solution that allows for users to navigate with right ToC even if it is very long
    - e.g. make scrollable or collapsible
![Untitled](https://user-images.githubusercontent.com/33759007/164245176-15a22df8-9762-4d85-9ed4-43586cdf14dd.png)

**Comment by fstau** [comment]
I'd propose making the right sidebar scrollable. Should be ~1-2h.
