### ISSUE TITLE
Allow for Descriptive Tab Titles

### ISSUE THREAD

**Issue by brandenchan** [deepset-ai/haystack-website#280]
- The tabs of each page only say Haystack Docs - it would be good if they were more specific!
    - e.g. Haystack - Pipelines
- Not sure how this is best implemented but it would be good to create some kind of mechanism so that we can easily add these tab titles also for newly created pages (whether in the Overview, API, Components, Guides or Tutorials sections)

![Screenshot from 2021-08-31 17-11-21](https://user-images.githubusercontent.com/33759007/164245545-ca32bb5e-ae88-469f-9ba4-b5ea03a33c45.png)

**Comment by fstau** [comment]
@brandenchan I have two ideas for this. If the h1 headlines in the mdx files can be used for the tab title, it would probably be the easiest to parse and use those. If you want more control we could agree on a format for an HTML comment that you could add at the top of your mdx documents e.g.

```html
<!-- 
meta_title: Haystack - Pipelines
meta_description: Pipelines
...
-->
```

With the latter approach we could also cover settings other meta tags in the head of the page for SEO purposes (e.g. meta description and tags). Whether this works in your document generation pipelines would need to be clarified.

For the simple approach I think ~2h should suffice, for the latter ~4h.
