### ISSUE TITLE
Image Resizing

### ISSUE THREAD

**Issue by brandenchan** [deepset-ai/haystack-website#281]
- All images and code boxes seem to adjust to however wide the window is
- This can look quite odd, especially when you set the window to fullscreen
- There should be something to limit images to a certain size
 
![Screenshot from 2021-08-31 17-10-45](https://user-images.githubusercontent.com/33759007/164245741-99c0682d-0078-4e8f-8402-ca8478c5e518.png)

**Comment by fstau** [comment]
@brandenchan we have control over the styling for all images, lets identify a few relevant examples that allow us to test a generic solution. Implementing and testing this once we know which cases we are trying to deal with should take no longer than ~1h.
My current assumption is that we might want to limit the max-height to the view height of the screen, but I am unsure whether this would have unwanted side-effects on other images.
