### ISSUE TITLE
Shorter Feedback Mechanism

### ISSUE THREAD

**Issue by brandenchan** [deepset-ai/haystack-website#285]
- We would like a more inviting way to let users ask questions about our documentation
- Let's have a box on the right like the "Edit on Github" box
    - It should say something like "Have a question? Start a Discussion!"
    - It should point to Haystack's Github Discussions ([here](https://github.com/deepset-ai/haystack/discussions))
    - Or as inspiration you could check out [what Milvus has done](https://milvus.io/docs/v2.0.0/comparison.md)

**Comment by fstau** [comment]
@brandenchan I think this will take ~1-2h
