### ISSUE TITLE
Reduce the number of Github API calls

### ISSUE THREAD

**Issue by brandenchan** [deepset-ai/haystack-website#289]
When deploying the website, many calls are made to the Github API to fetch files. Sometimes we hit the limit of allowed API calls thus causing our website not to build properly. Let's reduce the number of API calls, perhaps by fetching these files without the Github API so that this doesn't happen again.

**Comment by fstau** [comment]
I'd propose spending ~1h identifying possible root causes and solutions and then discussing how we approach this.

**Comment by TuanaCelik** [comment]
I've been trying to figure out the cause of this too and these findings might be useful for you @fstau 
Before though, here are a few things worth knowing:
- The API calls exceeding the limit at times doesn't cause the build to fail (you can try this with a production build locally)
- However the build has errors
- This seems to cause some paths in the website to produce 404s.
- Annoyingly this won't happen on a dev build all the time
- Good example of a 404 which currently doesn't 404 on a dev build is: https://haystack.deepset.ai/overview/v0.7.0/intro

The GitHub api requests are made for 2 sections of the website: the Tutorials and the API Reference (and some stargazers counts etc which is propably not the issue)
However, a request is made for each sub-section + every version. So, as the website grows, it becomes more and more requests that could maybe(?) handled more efficiently than what it is currently.

You can see these API call functions defined in `/lib/github.ts` e.g. the function `getDownloadUrl`

But then it's called from `/pages/reference/[..slug].tsx` and `/pages/tutorials/[..slug].tsx`. For each version + file individually. 
My guess is this is the issue. Hope that helps a bit. There might be a way to combine groups of requests into one.

**Comment by TuanaCelik** [comment]
And today you will notice that that URL I shared no longer 404s. Presumably there was a new deployment with less people developing at the same time and we didn't hit the limit. So the build was ok.
