### ISSUE TITLE
404s returned for all tutorial pages 

### ISSUE THREAD

**Issue by manisnesan** [deepset-ai/haystack-website#322]
https://haystack.deepset.ai/tutorials/fine-tuning-a-model -> Returning `404 - There's no doc for the page you requested.`

This is happening for all the pages under the Tutorial section.

**Comment by masci** [comment]
Hi @manisnesan and thanks for reporting!

The issue was mostly fixed in https://github.com/deepset-ai/haystack-website/pull/321, I'm keeping this open as we're still missing some pages that require a different fix.
