### ISSUE TITLE
Update knowledge graph page with InMemoryKnowledgeGraph

### ISSUE THREAD

**Issue by julian-risch** [deepset-ai/haystack-website#346]
Now that an InMemoryKnowledgeGraph was added in PR https://github.com/deepset-ai/haystack/pull/2678 by @anakin87 we should update the documentation page: https://haystack.deepset.ai/guides/knowledge-graph I would argue for replacing GraphDB with InMemoryKnowledgeGraph in most parts because it's much easier to set up. GraphDB should still be mentioned and its installation steps as well but the functionality is the same for both.

@agnieszka-m

**Comment by brandenchan** [comment]
Fixed by #350
