### ISSUE TITLE
Ensure same order of classes in API markdowns

### ISSUE THREAD

**Issue by tholor** [deepset-ai/haystack-website#37]
At the moment the sorting of classes seems to change between different runs of pydoc-markdown 

For example, in https://github.com/deepset-ai/haystack/pull/501/files the ElasticsearchDocumentstore moved from first position in the markdown to a later position. This complicates code reviews as the diff will be huge for tiny changes.

**Comment by PiffPaffM** [comment]
This was fixed in an old release. Not relevant anymore
