### ISSUE TITLE
Aesthetic Changes for Documentation Website

### ISSUE THREAD

**Issue by brandenchan** [deepset-ai/haystack-website#48]
- [x] Pick better font - try Lato
- [x] Bullet points seem too spaced out
- [x] Pick code font
- [x] Tabbed elements need borders (see DocumentStore/Choosing…)
- [x] Boxes around tips, tricks, recommendations
- [x] Make the hierarchy of different header/title levels clearer

**Comment by PiffPaffM** [comment]
@brandenchan I implemented some first ideas for these changes. Please have a look into our staging environment and then we can sync about it. Especially, we should talk about "Boxes around tips, tricks, recommendations". Here, we need to change the markdown files.
