### ISSUE TITLE
Define current deployment processes and automate gaps

### ISSUE THREAD

**Issue by brandenchan** [deepset-ai/haystack-website#80]
Let's define all the steps for editing and deploying our website

- [x] Create overview on Wiki
- [x] Document how different sources are handled (e.g. tutorials / docstrings / benchmarks)
- [x] Define some requirements on a good system (e.g. local development, scripts to locally pull latest changes from Haystack)
- [x] Definition of internal and external link protocols (e.g. best not to have links that point to github current master since this can change)
- [x] Plan work on improvements

- [x] Integrate docstring generation into deployment process (option to deploy it to staging) -> Bring all together in one script (@brandenchan) and trigger this script in Github actions (@PiffPaffM)
- [x] Integrate Tutorial generation into deployment process (option to deploy it to staging) -> Use Python script in Github Actions (@PiffPaffM)
- [x] Automate "Change File Process" -> Come up with initial design (@PiffPaffM)
- [ ] Automate "New File Process" -> Come up with initial design (@PiffPaffM)
- [x] Automate "New Version Process" -> Deployment to staging and then PR for haystack website (@PiffPaffM)

**Comment by PiffPaffM** [comment]
Link to wiki page. Still needs to be filled.
